version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
